server:
  port: 9555
spring:
  messages:
    basename: i18n/custom
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/kysy?useUnicode=true&characterEncoding=UTF-8  #数据库连接地址
      username: root   #数据库用户名
      password: mysqladmin   #数据库连接密码
      type: com.alibaba.druid.pool.DruidDataSource  #配置当前要使用的数据源的操作类型
      driver-class-name: org.gjt.mm.mysql.Driver  #配置MySQL的驱动程序类`
      dbcp2:   #进行数据库连接池的配置
        min-idle: 5    #数据库连接池的最小维持连接数
        initial-size: 5   #初始化提供的连接数
        max-total: 5   #最大的连接数
        max-wait-millis: 200   #等待连接获取的最大超时时间
    sqlserver:
      jdbc-url: jdbc:sqlserver://116.54.19.110:54330;DatabaseName=KY_SKZY_0229
      username: sa
      password: KYJT_yysygs177
      #使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  servlet:
    multipart:
      enabled: true   #启动上传配置
      max-file-size: 10MB #设置单个上传文件大小的限制
      max-request-size: 20MB #设置总体上传大小的限制
      file-size-threshold: 521KB #每当达到512KB的时候内容写入磁盘
      location: / #设置上传目录
  data:
   mongodb:
     host: 127.0.0.1
     database: kysy
     port: 27017
     username: sang
     password: 123
  redis:
    database: 0    #表示使用的Redis库的编号，Redis中提供了16个database，编号为0~15
    host: 192.168.40.173  #部署到服务器要换成服务器内网ip地址
    port: 6379
    password:
    #timeout: 5000
    jedis:
      pool:
        max-active: 8   #连接池最大连接数
        max-idle: 8     #连接池最大空闲连接数
        max-wait: -1   #连接池的最大阻塞等待时间 ，默认为-1，表示没有限制
        min-idle: 0     #连接池最小空闲连接



#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml    #mybatis配置文件所在路径
#  type-aliases-package: com.sygs.pojo      #定义所有操作类的别名所在包
#  mapper-locations: classpath:mybatis/mapper/**/*.xml  #所有的mapper映射文件

logging:
  level:
    com.sygs: debug
  file: E:/kysy/log.log

